### ISSUE TITLE
Add support for doas

### ISSUE THREAD

**Issue by wyndon** [MatthewCroughan/nixinate#1]
`doas` is an alternative to `sudo`.

**Comment by MatthewCroughan** [comment]
This is unlikely to be implemented, as we are settling on `nixos-rebuild` as an API for implementing Nixinate. This means that you would need to get `nixos-rebuild` to support doas, by modifying https://github.com/NixOS/nixpkgs/blob/nixos-21.11/pkgs/os-specific/linux/nixos-rebuild/nixos-rebuild.sh
