### ISSUE TITLE
attempting to add any app to a nixinate flake results in an error

### ISSUE THREAD

**Issue by DarthPJB** [MatthewCroughan/nixinate#17]
Create a flake using nixinate, then attempt to add an app
```nix
apps.x86_64-linux.exampleApp.type = "app";
apps.x86_64-linux.exampleApp.program = "echo hello";
```

the flake will no longer evaluate.

`` **error: attribute 'apps.x86_64-linux.deployEvilStaging.type' already defined** ``

**Comment by MatthewCroughan** [comment]
`nixinate` results in an attritbute set called `apps`. To add more to this set, you need to concatenate using `//`.

Here's two examples which are the exact same expression, but just done in a different order.
```
apps = nixinate.nixinate.x86_64-linux self // {
  x86_64-linux.exampleApp = {
    type = "app";
    program = "echo hello";
  };
};
```
```
apps.x86_64-linux = {
  exampleApp = {
    type = "app";
    program = "echo hello";
  };
} // nixinate.nixinate.x86_64-linux self;
```

**Comment by DarthPJB** [comment]
Oh wow, I learned something handy there!
Thanks
