### ISSUE TITLE
nixinate.me is an excellent domain that you guys can get for only 5$

### ISSUE THREAD

**Issue by gytis-ivaskevicius** [MatthewCroughan/nixinate#23]
I was just going through domains and thought that you guys may like this https://www.namecheap.com/domains/registration/results/?domain=nixinate.me

another good one would be `nixinate.xyz`

**Comment by MagicRB** [comment]
:+1: for nixinate.me, i give @MatthewCroughan 5 days, if he doesnt buy it, i will

**Comment by MagicRB** [comment]
well, wasn't 5 days, but its taken now

**Comment by MatthewCroughan** [comment]
I grabbed it the moment you suggested it :P

**Comment by MagicRB** [comment]
Sneaky fella

**Comment by gytis-ivaskevicius** [comment]
why nothing is hosted under that domain :eyes:
