### ISSUE TITLE
don't know how to build these path

### ISSUE THREAD

**Issue by happysalada** [MatthewCroughan/nixinate#37]
hey I've just updated to the latest nixinate master and it seems to be giving me the following error
```
don't know how to build these paths:
  /nix/store/cw9hr92idq1p5iady76xm4si9jqha2yw-nixos-rebuild
error: build of '/nix/store/cw9hr92idq1p5iady76xm4si9jqha2yw-nixos-rebuild' failed
```
Do I need to change anything ?

**Comment by MatthewCroughan** [comment]
@happysalada Can you do the following:

1. give me the output of `nix-info -m`
2. show me how you're using nixinate in your nixosConfiguration

**Comment by MatthewCroughan** [comment]
I should start versioning Nixinate, and it is something I intend to do, there's also a few things the VM Tests fail to catch as noted in #32, I'm working on a big update that uses recursive-nix and impure-derivations to perform deployments in the Nix sandbox, so watch this space.

**Comment by MatthewCroughan** [comment]
My suspicion is that I expect this issue to have something to do with the host-architecture you're deploying from, as the only change I've made recently is to make hermetic builds the default, which means a quick fix would be to set hermetic to `false` explicitly in your Nixinate arguments, if this is the case.

**Comment by happysalada** [comment]
that was indeed what broke it. I have no idea what hermetic is, but you can't do it on a remote build apparently.
Thanks for the quick response!

**Comment by MatthewCroughan** [comment]
@happysalada Hermetic is documented in the README. What it will do is copy `nix` and `nixos-rebuild` to the remote machine, rather than impurely executing the nixos-rebuild on the remote machine, assuming it is there.k

**Comment by happysalada** [comment]
oh that makes sense, I'm on a darwin machine and trying to build on a linux machine. That's why it doesn't work. Ok, thanks for the explanation!
