### ISSUE TITLE
When installing on small VPS, (RAM) disk runs full. Solve by supporting disko and /mnt?

### ISSUE THREAD

**Issue by ppenguin** [MatthewCroughan/nixinate#41]
See title, this would be an ideal use case (for me pretty much the most likely one, since it is likely to be more often repeated than for own hardware).

**Comment by ppenguin** [comment]
Ah thanks, might have been an misunderstanding about functionality, I wanted to use it to do a "one-click-provisioning" on a vps from a finished `nixosConfigurations.myvps`, but I was able to do that flawlessly with [`nixos-anywhere`](https://github.com/numtide/nixos-anywhere), including auto-partitioning with `disko`.

So tthe main use case of `nixinate` is to basically "include" the functionality I do now with
```
NIX_SSHOPTS=-t nixos-rebuild switch --target-host myfqdn --use-remote-sudo --flake .#myvps1
```
in the flake in order to make remote updates/reconfigs more ergonomical?

**Comment by MatthewCroughan** [comment]
@ppenguin that's pretty much it for now yeah, and you could do provisioning in the new nixinate in idempotent pre-deploy scripts, if you wanted. I'm working hard on it, but only have so much time.
