### ISSUE TITLE
nix copy just hangs with latest nix stable

### ISSUE THREAD

**Issue by happysalada** [MatthewCroughan/nixinate#43]
testing with latest nixpkgs unstable, and nix run .#app.nixinate.my_host
just hangs on the line
```
/nix/store/yxyyb12wn2zxq8dasrv4r9dx7x7vwd2i-nix-2.15.1/bin/nix copy /nix/store/p9xgyp1y3vj1c2y3aar84nly4z4848qm-source --to ssh://yt@bee
```
I don't know since when it's been happening, just got his trying to deploy today.

**Comment by MatthewCroughan** [comment]
This is definitely a Nix bug. Use an older version of Nix for now. Anecdotally, I have ran into this with `nix copy`, and I have a hunch that it has something to do with signatures/auth when performing the copy.

**Comment by happysalada** [comment]
Yeah it doesnt happen all the time, very weird.
Im good, happy to close this if you prefer

**Comment by MatthewCroughan** [comment]
Given as it's an upstream Nix issue, it's best to close it yeah.
